### ISSUE TITLE
emacs hangs on contacting host if using https

### ISSUE THREAD

**Issue by tinnus-napbus** [clonex10100/urbit-api.el#2]
I can connect to a local ship fine over ordinary http but if I try to connect to my main ship on a server with tls then emacs permanently hangs and must killed from the terminal

**Comment by clonex10100** [comment]
What kind of https are you using? My ship is on a server behind an apache https reverse proxy and it works.

**Comment by tinnus-napbus** [comment]
it's just an nginx reverse proxy with tls configured by the letsencrypt certbot

**Comment by tinnus-napbus** [comment]
a few other people reported the same thing - I assumed it was an https issue but maybe it's something else

**Comment by tinnus-napbus** [comment]
one of your recent commits fixed this - sse race condition maybe
